Models/KennelModels/Kennel.cs
using CCP.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace CCP.Models.KennelModels
{
	public class Kennel
	{
        public int ID { get; set; }
        public int CountryID { get; set; }
        public string Name { get; set; }
        public string OwnerName { get; set; }
        public string WebsiteURL { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string About { get; set; }

        public ImagesMetaData? Logo { get; set; }
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public CCPUser User { get; set; }
        public Country Country { get; set; }
    }
}

Controllers/KennelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CCP.Data;
using CCP.Models.KennelModels;
using CCP.ViewModels;
using Amazon.S3;
using Amazon;
using Amazon.S3.Transfer;
using CCP.Models;
using Amazon.S3.Model;
using Microsoft.AspNetCore.Identity;
using CCP.Areas.Identity.Data;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;
using CCP.Models.DogModels;
using Newtonsoft.Json;

namespace CCP.Controllers
{
    public class KennelsController : Controller
    {
        private readonly CCPContext _context;
        private readonly IConfiguration _configuration;
        private readonly UserManager<CCPUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public KennelsController(CCPContext context, IConfiguration configuration, UserManager<CCPUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _configuration = configuration;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Kennels
        public async Task<IActionResult> Index(string search = "", string country = "")
        {
            var query = _context.Kennel
        .Where(k => k.Name.Contains(search));

            if (!string.IsNullOrWhiteSpace(country) && country != "All Countries")
            {
                query = query.Where(k => k.Country.Name == country);
            }

            query = query.Include(k => k.Logo)
                         .Include(k => k.Country);

            ViewBag.Countries = _context.Kennel.Select(k => k.Country.Name).Distinct()
                   .OrderBy(name => name)
                   .Select(name => new SelectListItem
                   {
                       Value = name,
                       Text = name
                   }).ToList();

            return View(await query.ToListAsync());
        }

        // GET: Kennels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Kennel == null)
            {
                return NotFound();
            }

            var kennel = await _context.Kennel
                .Include(k => k.Country)
                .Include(k => k.Logo)
                .Include(k => k.User)
                .FirstOrDefaultAsync(m => m.ID == id);
            List<Dog> dogs = await _context.Dog.Where(d => d.KennelID == kennel.UserId).ToListAsync();
            
            ViewData["KennelDogs"] = dogs;
            if (kennel == null)
            {
                return NotFound();
            }

            return View(kennel);
        }

        // GET: Kennels/Create
        public async Task<IActionResult>  Create()
        {
            //Get user
            var user = await _userManager.GetUserAsync(User);
            if(user != null)
            {
                //Get user kennel
                var userKennel = await _context.Kennel.FirstOrDefaultAsync(k => k.UserId == user.Id);
                if (userKennel != null)
                {
                    return RedirectToAction(nameof(Details), new { id = user.Kennel.ID });
                }
            }
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "Name");
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KennelLogoVM vm)
        {
            try
            {
                var user = await _context.User.FirstOrDefaultAsync(u => u.Id == vm.Kennel.UserId);

                if (user == null || user.Id != vm.Kennel.UserId)
                {
                    return RedirectToAction("Login", "Account");
                }
                if (vm.Kennel != null)
                {
                    Kennel newKennel = vm.Kennel;
                    Kennel kennelWithSameName = await _context.Kennel.FirstOrDefaultAsync(k => k.Name == newKennel.Name);

                    if (vm.Logo != null)
                    {
                            var imageName = Guid.NewGuid().ToString() + Path.GetExtension(vm.Logo.FileName);
                            var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
                            Directory.CreateDirectory(uploadsFolder); // Create the directory if it doesn't exist
                            var imagePath = Path.Combine(uploadsFolder, imageName);
                            using (var stream = new FileStream(imagePath, FileMode.Create))
                            {
                                await vm.Logo.CopyToAsync(stream);
                            }
                            ImagesMetaData imagesMetaData = new ImagesMetaData { Name = imageName, ImagePath = imagePath, UploadDate = DateTime.Now, Kennel = vm.Kennel };
                        
                        _context.Add(imagesMetaData);
                    }
                    _context.Add(newKennel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch(DbUpdateException ex)
            {
                // Check if the exception is due to a unique constraint violation
                var innerException = ex.InnerException;
                if (innerException != null && innerException is SqlException sqlEx &&
                    (sqlEx.Number == 2601 || sqlEx.Number == 2627)) // These numbers correspond to unique constraint violations
                {
                    ModelState.AddModelError("Kennel.Name", "The kennel name is already taken.");
                }
                else
                {
                    // Handle other types of database exceptions or log the error
                    ModelState.AddModelError(string.Empty, "An error occurred while saving. Please try again.");
                }
            }
            
            
            ViewData["CountryID"] = new SelectList(_context.Country, "ID", "ID", vm.Kennel.CountryID);
            return View(vm);
        }

        // GET: Kennels/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _context.User.Include(u => u.Kennel).FirstOrDefaultAsync(u => u.Kennel.ID == id);
            if(user == null)
            {
                return RedirectToAction("Login", "Account");

            }
            if (user.Kennel == null)
            {
                return RedirectToAction(nameof(Index));
            }
           
            if (id == null || _context.Kennel == null)
            {
                return NotFound();
            }

            var kennel = await _context.Kennel.Include(k => k.Logo).FirstOrDefaultAsync(k => k.ID == id);
            if (kennel == null)
            {
                return NotFound();
            }
            KennelLogoVM vm = new KennelLogoVM
            {
                Kennel = kennel
            };
            ViewData["CountryID"] = new SelectList(_context.Country.ToList(), "ID", "Name", kennel.CountryID);
            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, KennelLogoVM vm)
        {
            if (id != vm.Kennel.ID)
            {
                return NotFound();
            }
            
            if(vm.Kennel != null)
            {
                try
                {
                    var user = await _context.User.Include(u => u.Kennel).FirstOrDefaultAsync(u => u.Kennel.ID == id);
                    //get kennel before changes for comparison
                    var originalKennelBeforeChanges = _context.Kennel.AsNoTracking().Include(k => k.Logo)
                        .FirstOrDefault(k => k.ID == id);
                    // Handle kennel details update
                    var existingKennel = await _context.Kennel.Include(k => k.Logo).FirstOrDefaultAsync(k => k.ID == id);

                    if (existingKennel == null)
                    {
                        return NotFound();
                    }

                    existingKennel.Name = vm.Kennel.Name;
                    existingKennel.OwnerName = vm.Kennel.OwnerName;
                    existingKennel.CountryID = vm.Kennel.CountryID;
                    existingKennel.WebsiteURL = vm.Kennel.WebsiteURL;
                    existingKennel.Address = vm.Kennel.Address;
                    existingKennel.Phone = vm.Kennel.Phone;
                    existingKennel.Mobile = vm.Kennel.Mobile;
                    existingKennel.About = vm.Kennel.About;

                    if (vm.Logo != null && vm.Logo.Length > 0)
                    {
                        string bucketName = "ccpgroupbucket";
                        var accessKey = _configuration["AwsAccessKey"];
                        var secretKey = _configuration["AwsSecretKey"];
                        using (var client = new AmazonS3Client(accessKey, secretKey, RegionEndpoint.EUNorth1))
                        {
                            var imageName = Guid.NewGuid().ToString() + Path.GetExtension(vm.Logo.FileName);
                            var fileTransfer = new TransferUtility(client);

                            using (var stream = vm.Logo.OpenReadStream())
                            {
                                await fileTransfer.UploadAsync(stream, bucketName, imageName);
                            }
                            // Update the logo information in the existing kennel
                            if (existingKennel.Logo != null)
                            {
                                if (existingKennel.Logo.Name != imageName || existingKennel.Logo.ImagePath != $"https://{bucketName}.s3.amazonaws.com/{imageName}")
                                {

Views/Kennels/Create.cshtml
@model CCP.ViewModels.KennelLogoVM

@{
    ViewData["Title"] = "Create";
}
@using Microsoft.AspNetCore.Identity
@using CCP.Areas.Identity.Data

@inject SignInManager<CCPUser> SignInManager
@inject UserManager<CCPUser> UserManager

<h1>Create</h1>

<h4>Kennel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Kennel.CountryID" class="control-label"></label>
                <select asp-for="Kennel.CountryID" class ="form-control" asp-items="ViewBag.CountryID">
                    <option>-- Select country --</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Name" class="control-label"></label>
                <input asp-for="Kennel.Name" class="form-control" />
                <span asp-validation-for="Kennel.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.OwnerName" class="control-label"></label>
                <input asp-for="Kennel.OwnerName" class="form-control" />
                <span asp-validation-for="Kennel.OwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.WebsiteURL" class="control-label"></label>
                <input asp-for="Kennel.WebsiteURL" class="form-control" />
                <span asp-validation-for="Kennel.WebsiteURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Address" class="control-label"></label>
                <input asp-for="Kennel.Address" class="form-control" />
                <span asp-validation-for="Kennel.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Phone" class="control-label"></label>
                <input asp-for="Kennel.Phone" class="form-control" />
                <span asp-validation-for="Kennel.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Mobile" class="control-label"></label>
                <input asp-for="Kennel.Mobile" class="form-control" />
                <span asp-validation-for="Kennel.Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.About" class="control-label"></label>
                <input asp-for="Kennel.About" class="form-control" />
                <span asp-validation-for="Kennel.About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label">Logo</label>
                <input asp-for="Logo" type="file" class="form-control" accept=".jpg, .jpeg, .png" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                var user = await UserManager.GetUserAsync(User);
                var userId = await UserManager.GetUserIdAsync(user);
                <input type="hidden" asp-for="Kennel.UserId" value="@userId" />
            }
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kennels/Delete.cshtml
@model CCP.Models.KennelModels.Kennel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kennel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebsiteURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Kennels/Details.cshtml
@model CCP.Models.KennelModels.Kennel

@{
    ViewData["Title"] = "Details";
    var kennelDogs = ViewBag.KennelDogs as List<Dog>;
}
@using Microsoft.AspNetCore.Identity
@using CCP.Areas.Identity.Data
@using CCP.Models.DogModels

@inject SignInManager<CCPUser> SignInManager
@inject UserManager<CCPUser> UserManager
<h1>Details</h1>

<div>
    <h4>Kennel</h4>
    @if(Model.Logo != null)
    {
        <div class="col-sm-10">
            <img src="@Url.Action("GetLogo", "Kennels", new{logoName = Model.Logo.Name})" alt="Kennel Logo" width="100px" height="100px"/>
        </div>
    }
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebsiteURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
        <dt class = "col-sm-2">
            Dogs
        </dt>
        <dd class = "col-sm-10">
            <ul>
                @if (kennelDogs != null)
                {
                    @foreach (var dog in kennelDogs)
                    {
                        <li><a asp-action="Details" asp-controller="Dog" asp-route-Id="@dog.ID">@dog.RegName</a></li>
                    }
                }
                else
                {
                    <li>No dogs in this kennel</li>
                }

            </ul>
        </dd>
       
    </dl>
</div>
<div>
    @if (SignInManager.IsSignedIn(User))
    {
        var user = await UserManager.GetUserAsync(User);
        var userId = await UserManager.GetUserIdAsync(user);
        if (user == Model.User)
        {
            <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a>
            <span>|</span>
            <a asp-action = "Index" > Back to List</a>
        }
        else
        {
            <a asp-action="Index"> Back to List</a>
        }
    }
    else
    {
        <a asp-action="Index"> Back to List</a>
    }

</div>

Views/Kennels/Edit.cshtml
@model CCP.ViewModels.KennelLogoVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Kennel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Kennel.ID" />
            <div class="form-group">
                <label asp-for="Kennel.CountryID" class="control-label"></label>
                <select asp-for="Kennel.CountryID" class="form-control" asp-items="ViewBag.CountryID"></select>
                <span asp-validation-for="Kennel.CountryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Name" class="control-label"></label>
                <input asp-for="Kennel.Name" class="form-control" />
                <span asp-validation-for="Kennel.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.OwnerName" class="control-label"></label>
                <input asp-for="Kennel.OwnerName" class="form-control" />
                <span asp-validation-for="Kennel.OwnerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.WebsiteURL" class="control-label"></label>
                <input asp-for="Kennel.WebsiteURL" class="form-control" />
                <span asp-validation-for="Kennel.WebsiteURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Address" class="control-label"></label>
                <input asp-for="Kennel.Address" class="form-control" />
                <span asp-validation-for="Kennel.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Phone" class="control-label"></label>
                <input asp-for="Kennel.Phone" class="form-control" />
                <span asp-validation-for="Kennel.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.Mobile" class="control-label"></label>
                <input asp-for="Kennel.Mobile" class="form-control" />
                <span asp-validation-for="Kennel.Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kennel.About" class="control-label"></label>
                <input asp-for="Kennel.About" class="form-control" />
                <span asp-validation-for="Kennel.About" class="text-danger"></span>
            </div>
            @if (Model.Kennel.Logo != null)
            {
                <div class="col-sm-10">
                    <img src="@Url.Action("GetLogo", "Kennels", new { logoName = Model.Kennel.Logo.Name })" alt="Kennel Logo" width="50px" height="50px" />
                </div>
            }
            <div class="form-group mb-3">
                <label asp-for="@Model.Logo" class="control-label">Logo</label>
                <input asp-for="@Model.Logo" type="file" class="form-control" id="inputImage" accept=".jpg, .jpeg, .png">
                <span asp-validation-for="@Model.Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kennels/Index.cshtml
@model IEnumerable<CCP.Models.KennelModels.Kennel>

@{
    ViewData["Title"] = "Index";
}
@using Microsoft.AspNetCore.Identity
@using CCP.Areas.Identity.Data

@inject SignInManager<CCPUser> SignInManager
@inject UserManager<CCPUser> UserManager

<h1>Kennel Registry</h1>

<div class="row text-end">
    @using (Html.BeginForm("Index", "Kennels", FormMethod.Get))
    {
        <p>
            Search: @Html.TextBox("search")
            <input type="submit" value="Filter" />
        </p>
        <p>
            Country: @Html.DropDownList("country", new SelectList(ViewBag.Countries, "Value", "Text"), "All Countries")
            <input type="submit" value="Filter by Country" />
        </p>
    }
</div>



<p>
    @if (SignInManager.IsSignedIn(User))
    {
        var user = await UserManager.GetUserAsync(User);
        var userId = await UserManager.GetUserIdAsync(user);
        if(user.Kennel != null)
        {
            <a asp-action="Details" asp-route-id="@user.Kennel.ID"> Your kennel </a>
        }
        else
        {
            <a asp-action="Create">Create New</a>
        }
    }
    else
    {
        <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login to add kennel</a>
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WebsiteURL)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                    @if(item.Logo != null)
                    {
                        <img src="@Url.Action("GetLogo", "Kennels", new{logoName = item.Logo.Name})" alt="Kennel Logo" width="60px" height="60px" />
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WebsiteURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.Name)
            </td>
            <td>
                    
                    @if (SignInManager.IsSignedIn(User))
                    {
                        var user = await UserManager.GetUserAsync(User);
                        var userId = await UserManager.GetUserIdAsync(user);
                        if(user.Kennel == item)
                        {
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                            <span>|</span>
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                            <span>|</span>
                            <a asp-action="Details" asp-route-id="@item.ID" > Details </a> 
                        }else
                        {
                            <a asp-action="Details" asp-route-id="@item.ID"> Details </a>
                        }
                    }
                    else if(!SignInManager.IsSignedIn(User))
                    {
                        <a asp-action="Details" asp-route-id="@item.ID"> Details </a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>